site_name: DNUM
site_url: https://dnum.cutel.net
repo_url: https://github.com/cu-telecom/dnum-wiki
nav:
  - About: index.md
  - Technical Overview:
    - technical/numbering.md
    - technical/index.md
    - technical/routing.md
    - technical/verification.md
    - technical/encryption_authentication.md
  # - Configuration:
    # - configuration/index.md
    # - configuration/stirshaken.md
markdown_extensions:
  - pymdownx.tilde
  - attr_list
  - md_in_html
plugins:
  - search
theme:
  name: material
  logo: assets/full-logo-light.svg
  #favicon: assets/logo-dark.svg
  palette:
    primary: black
  features:
    - toc.integrate
    - navigation.top
    - navigation.indexes 
    #- navigation.expand
  custom_dir: ./overrides
extra:
  navigation:
    hide: navigation